version: "3.7"

services:
  app:
    image: indapublic/docker-swarm-expose-test-nextjs:test
    ports:
      - 3000:3000
      - 3001:3001
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
