version: "3.7"

services:
  app:
    image: indapublic/docker-swarm-expose-test:latest
    ports:
      - 3000:3000
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
